# Generated by Django 5.1.3 on 2024-12-09 08:15

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name="RecordFormConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Имя конфигурации",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("phone", models.BooleanField(default=False)),
                ("full_name", models.BooleanField(default=False)),
                ("department", models.BooleanField(default=False)),
                ("position", models.BooleanField(default=False)),
                ("room", models.BooleanField(default=False)),
                ("email", models.BooleanField(default=False)),
                ("image", models.BooleanField(default=False)),
                ("expire_time_duration", models.IntegerField(default=1)),
                ("attempts_number", models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=500)),
                ("prev_values", models.JSONField(blank=True, null=True)),
                ("next_values", models.JSONField(blank=True, null=True)),
                ("slug", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=24)),
                ("logged_in_code", models.CharField(max_length=40)),
                (
                    "by_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("full_name", models.CharField(max_length=100)),
                ("position", models.CharField(blank=True, max_length=200)),
                (
                    "position_id",
                    models.IntegerField(blank=True, default=1, verbose_name="Позиция"),
                ),
                ("room", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="records/"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ipphone_app.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4)),
                ("attempt_numbers", models.IntegerField(default=0)),
                (
                    "expire_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 12, 9, 8, 15, 58, 467837, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("phone", models.BooleanField(default=False)),
                ("full_name", models.BooleanField(default=False)),
                ("department", models.BooleanField(default=False)),
                ("position", models.BooleanField(default=False)),
                ("room", models.BooleanField(default=False)),
                ("email", models.BooleanField(default=False)),
                ("image", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipphone_app.record",
                    ),
                ),
            ],
        ),
    ]
