# Generated by Django 5.1.4 on 2024-12-21 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipphone_app', '0003_alter_record_email_alter_record_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='room',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(code='invalid_room', message='Номер кабинета должна быть в формате А-234', regex='^[А-Я]-\\d{3}$')]),
        ),
    ]
