# Generated by Django 5.1.4 on 2024-12-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipphone_app', '0004_alter_record_phone_alter_record_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Статус занятости'),
        ),
    ]
